### ISSUE TITLE
Migrate to support Godot 4

### ISSUE THREAD

**Issue by staticpo** [tavurth/godot-simple-state#1]
Godot 4 is fast approaching a stable version and I would love to see this plugin support the new code conventions and features of the lastest Godot version.

Much appreciated.

**Comment by tavurth** [comment]
I guess I will switch over every repository when Godot hits stable 4.x.

Until that time, I have tried many times to use Godot 4 but every time it comes up failing my projects.

When I switch over my current projects to the next version everything will be updated.

**Comment by tavurth** [comment]
While I do not yet consider `4.x` game-jam ready.

[This branch contains 4.x compatible code](https://github.com/tavurth/godot-simple-state/tree/4.x) and will become the default in the near future.
